### ISSUE TITLE
Warnings 

### ISSUE THREAD

**Issue by Sergiodeavilac** [jahrTeaching/milestones-Sergiodeavilac#1]
Tras aplicar la función que define F (ya empleada en los métodos de Euler y runge-kutta de orden 2 y 4) en la función fsolve de scipy, se crean unos warnings relacionados con la extensión de las cifras que puede manejar, dándose como resultado que devuelva la matriz U  con todas sus columnas las condiciones iniciales.

**Comment by jahrWork** [comment]
Milestone1 is devoted to integrate without functions. Milestone2 with functions as you did. However, you are missing Cauchy_problem function which integrates with any temporal scheme such as Euler or Rk4. Two different abstractions. 
We will work on it this week.
